name: CD

on:  # yamllint disable-line rule:truthy
  # From documentation:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  # on.push.tags: If you define only tags/tags-ignore or only branches/branches-ignore, the workflow won't run for events affecting the undefined Git ref.
  #
  # This workflow will only run when a tag matching the criteria is pushed
  push:
    tags: ["v?[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install `pypa/build`
        run: python -m pip install build
      - name: Build sdist and wheel
        run: python -m build --sdist --wheel --outdir ./dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
